#!/usr/bin/env bash
# configures an Nginx web server to redirect
# any /redirect_me query to a specific url
sudo apt-get update -y
sudo apt-get install nginx -y
sudo ufw allow "Nginx HTTP"
echo "Hello World!" > /var/www/html/index.html
sed -i "/listen 80/a \
location /redirect_me { return 301 https//:www.google.com }"
sudo service nginx start
