#!/usr/bin/env bash
# installs the load balancer
apt-get -y update
apt-get -y install haproxy
echo '
frontend sammykingx.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 515469-web-01 100.26.152.157:80
        server 515469-web-02 52.86.102.6:80
' >> /etc/haproxy/haproxy.cfg
 service haproxy start
