#!/usr/bin/env bash
#a Bash script that displays the PID, along with the process name, of processes whose name contain the word bash
for pid_dir in /proc/*/; do
    pid=$(basename "$pid_dir")
    if [[ "$pid" =~ ^[0-9]+$ ]]; then
        process_name=$(cat "$pid_dir/comm" 2>/dev/null)
        if [[ "$process_name" == *"bash"* ]]; then
            echo "PID: $pid, Process Name: $process_name"
        fi
    fi
done
