#!/usr/bin/env bash

pkill 4-to_infinity_and_beyond

if pgrep 4-to_infinity_and_beyond >/dev/null; then
    echo "Failed to stop the process."
else
    echo "Process 4-to_infinity_and_beyond stopped."
fi
