#!/usr/bin/env bash
#a Bash script that displays the content of the file /etc/passwd
file="/etc/passwd"
if [ -e "$file" ]; then
    while IFS=: read -r username _ userid _ homedir _; do
        echo "Username: $username"
        echo "User ID: $userid"
        echo "Home Directory: $homedir"
    done < "$file"
else
    echo "File $file does not exist."
fi
