#!/usr/bin/env bash
#a Bash script that displays the content of the file /etc/passwd, using the while loop + IFS
file="/etc/passwd"
if [ -e "$file" ]; then
    while IFS=: read -r username _ groupid _ homedir shell; do
        user_info=$(grep "^$username:" /etc/passwd | cut -d ':' -f 5)
        password=$(grep "^$username:" /etc/shadow | cut -d ':' -f 2)
        echo "The user $username is part of the group $groupid gang, lives in $homedir and rides $shell. User ID's place is protected by the passcode $password, more info about the user here: $user_info"
    done < "$file"
else
    echo "File $file does not exist."
fi
